
# Copyright (c) 2026, PostgreSQL Global Development Group

# Test that ycmdb.wal_write_rate_lim actually throttles WAL generation.

use strict;
use warnings FATAL => 'all';

use PostgreSQL::Test::Cluster;
use PostgreSQL::Test::Utils;
use Test::More;

my $node = PostgreSQL::Test::Cluster->new('wal_rate_lim');
$node->init;
$node->append_conf(
	'postgresql.conf', qq(
synchronous_commit = off
wal_compression = off
max_wal_size = 4GB
));
$node->start;

$node->safe_psql('postgres', 'CREATE TABLE z(a text);');

# Generate a ~7MB data file on the server side.
my $datfile = $node->data_dir . '/dat.dat';
$node->command_ok(
	[ 'bash', '-c', "yes 2 | head -700000 > $datfile" ],
	'generate test data file');

# Baseline: no limit.  Measure WAL generated by a single COPY.
$node->safe_psql('postgres', "TRUNCATE z; CHECKPOINT;");
my $lsn_before = $node->safe_psql('postgres',
	"SELECT pg_current_wal_insert_lsn();");

my $t0 = time();
$node->safe_psql('postgres', "COPY z FROM '$datfile';");
my $t1 = time();

my $lsn_after = $node->safe_psql('postgres',
	"SELECT pg_current_wal_insert_lsn();");

my $wal_bytes_nolim = $node->safe_psql('postgres',
	"SELECT pg_wal_lsn_diff('$lsn_after'::pg_lsn, '$lsn_before'::pg_lsn);");
$wal_bytes_nolim =~ s/\s+//g;

my $elapsed_nolim = $t1 - $t0;
$elapsed_nolim = 1 if $elapsed_nolim == 0;
my $rate_nolim = int($wal_bytes_nolim / $elapsed_nolim);

diag("no limit: $wal_bytes_nolim bytes in ${elapsed_nolim}s = $rate_nolim B/s");
ok($rate_nolim > 1024 * 1024, 'baseline WAL rate exceeds 1MB/s without limit');

# Now set a 1MB/s limit and repeat.  Use a long timeout since the COPY
# will be throttled.
$node->safe_psql('postgres',
	"ALTER SYSTEM SET ycmdb.wal_write_rate_lim = '1MB';");
$node->safe_psql('postgres', 'SELECT pg_reload_conf();');

$node->safe_psql('postgres', "TRUNCATE z; CHECKPOINT;");
$lsn_before = $node->safe_psql('postgres',
	"SELECT pg_current_wal_insert_lsn();");

$t0 = time();
$node->safe_psql('postgres', "COPY z FROM '$datfile';",
	timeout => $PostgreSQL::Test::Utils::timeout_default * 6);
$t1 = time();

$lsn_after = $node->safe_psql('postgres',
	"SELECT pg_current_wal_insert_lsn();");

my $wal_bytes_lim = $node->safe_psql('postgres',
	"SELECT pg_wal_lsn_diff('$lsn_after'::pg_lsn, '$lsn_before'::pg_lsn);");
$wal_bytes_lim =~ s/\s+//g;

my $elapsed_lim = $t1 - $t0;
$elapsed_lim = 1 if $elapsed_lim == 0;
my $rate_lim = int($wal_bytes_lim / $elapsed_lim);

diag("1MB/s limit: $wal_bytes_lim bytes in ${elapsed_lim}s = $rate_lim B/s");

# The effective rate must not exceed 2MB/s (2x the configured limit, generous).
my $max_allowed = 2 * 1024 * 1024;
ok($rate_lim <= $max_allowed,
   "WAL rate with 1MB/s limit ($rate_lim B/s) does not exceed 2MB/s");
ok($rate_lim < $rate_nolim,
   "WAL rate with limit ($rate_lim B/s) is lower than baseline ($rate_nolim B/s)");

# Cleanup.
$node->safe_psql('postgres', 'DROP TABLE z;');
$node->stop;
done_testing();
