#-------------------------------------------------------------------------
#
# Makefile for src/backend/encrypt
#
# src/backend/encrypt/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/encrypt
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	$(WIN32RES) \
	encrypt_module.o \
	shell_encrypt.o

include $(top_srcdir)/src/backend/common.mk
